// <auto-generated />
using System;
using ElectroApiTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplianceAPI.Migrations
{
    [DbContext(typeof(ElectroContext))]
    [Migration("20220909192435_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ElectroApiTest.Models.Appliance", b =>
                {
                    b.Property<string>("ApplianceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("FactoryNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplianceID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Appliances");

                    b.HasData(
                        new
                        {
                            ApplianceID = "YS2R4X20005399401",
                            CustomerID = 1L,
                            FactoryNo = "ABC123"
                        },
                        new
                        {
                            ApplianceID = "VLUR4X20009093588",
                            CustomerID = 1L,
                            FactoryNo = "ABC123"
                        },
                        new
                        {
                            ApplianceID = "VLUR4X20009048066",
                            CustomerID = 1L,
                            FactoryNo = "GHI789"
                        },
                        new
                        {
                            ApplianceID = "YS2R4X20005388011",
                            CustomerID = 2L,
                            FactoryNo = "JKL012"
                        },
                        new
                        {
                            ApplianceID = "YS2R4X20005387949",
                            CustomerID = 2L,
                            FactoryNo = "MNO345"
                        },
                        new
                        {
                            ApplianceID = "YS2R4X20009048066",
                            CustomerID = 3L,
                            FactoryNo = "PQR678"
                        },
                        new
                        {
                            ApplianceID = "YS2R4X20005387055",
                            CustomerID = 3L,
                            FactoryNo = "STU901"
                        });
                });

            modelBuilder.Entity("ElectroApiTest.Models.ApplianceStatus", b =>
                {
                    b.Property<int>("ApplianceStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplianceStatusID"), 1L, 1);

                    b.Property<string>("ApplianceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfStatus")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ApplianceStatusID");

                    b.HasIndex("ApplianceID");

                    b.ToTable("ApplianceStatuses");
                });

            modelBuilder.Entity("ElectroApiTest.Models.Customer", b =>
                {
                    b.Property<long>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1L,
                            Name = "Kalles Grustransporter AB Cementvägen 8, 111 11 Södertälje"
                        },
                        new
                        {
                            CustomerID = 2L,
                            Name = "Johans Bulk AB Balkvägen 12, 222 22 Stockholm"
                        },
                        new
                        {
                            CustomerID = 3L,
                            Name = "Haralds Värdetransporter AB Budgetvägen 1, 333 33 Uppsala"
                        });
                });

            modelBuilder.Entity("ElectroApiTest.Models.Appliance", b =>
                {
                    b.HasOne("ElectroApiTest.Models.Customer", "Customer")
                        .WithMany("Appliances")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ElectroApiTest.Models.ApplianceStatus", b =>
                {
                    b.HasOne("ElectroApiTest.Models.Appliance", "Appliance")
                        .WithMany("ApplianceStatuses")
                        .HasForeignKey("ApplianceID");

                    b.Navigation("Appliance");
                });

            modelBuilder.Entity("ElectroApiTest.Models.Appliance", b =>
                {
                    b.Navigation("ApplianceStatuses");
                });

            modelBuilder.Entity("ElectroApiTest.Models.Customer", b =>
                {
                    b.Navigation("Appliances");
                });
#pragma warning restore 612, 618
        }
    }
}
